### ISSUE TITLE
Feature Request: dictionaries support for VariablesSubstitution

### ISSUE THREAD

**Issue by tsvx** [drwatson1/configuration-extensions#2]
E.g., `Dictionary<TKey,TValue>`

For instance, for this class
```csharp
public class ImageSettings
{
    public string Directory { get; set; }
    public Dictionary<ImageType, string> ImagePaths { get; set; }
}

public enum ImageType { Full, Cropped }
```
`AddOptions()` and `AutoBind()` work fine, but `SubstituteVariables()` gives the following error on the option resolution:
```
System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Contrib.Extensions.Configuration.VariablesSubstitution.OptionConfigurator.Configure[TOption](TOption option)
   at Contrib.Extensions.Configuration.VariablesSubstitution.OptionConfigurator.Configure[TOption](TOption option)
   at Contrib.Extensions.Configuration.VariablesSubstitutionExtensions.<>c__0`1.<SubstituteVariables>b__0_0(TOption opt, IOptionConfigurator conf)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`2.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
   at FakeImage.Startup.Configure(IApplicationBuilder app, ILogger`1 logger) in ..\FakeImage\Startup.cs:line 160
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
```
which is described [on the docs](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.propertyinfo.getvalue?view=netcore-3.1#System_Reflection_PropertyInfo_GetValue_System_Object_) (see Remarks section).

**Comment by drwatson1** [comment]
Thank you for the report. I've released version 1.2.0 with dictionary support.
